from easydict import EasyDict as edict

__APP_SETTINGS__ = edict()

__APP_SETTINGS__.DOTS_HISTORY = 300

__APP_SETTINGS__.ROI_XY_MIN = (0,0)#(357,466)
__APP_SETTINGS__.ROI_XY_MAX = (999999999,999999999) #(2038,1103)

__APP_SETTINGS__.VIDEO_PATH = "generated_videos"

__APP_SETTINGS__.VIDEO_SAVE_FRAMES_THRESH = 100

__APP_SETTINGS__.FRAMES_TO_PERSIST = 1

__APP_SETTINGS__.EXCEL_DIR = "report_excel"

__APP_SETTINGS__.EXCEL_NAME = "Data.csv"